# -*- coding: utf-8 -*-
"""TEK_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKF30izFspcGDbtYWTiZsJqdXpRh06It
"""

import requests
from bs4 import BeautifulSoup, Comment
import pandas as pd


# This is the working one-year version:
# The original script fetches and parses the passing stats table for a single year.
# You manually specify the year (e.g., 2025) in the URL, scrape the table, convert it
#  to a DataFrame, and save it. It only handles one season at a time, so you’d need
#  to run it separately for each year you’re interested in.


# 1. The URL found in your source code
url = "https://www.spotrac.com/nba/rankings/player/_/year/2025/sort/cap_total"
# 2. Set headers so Spotrac thinks we are a real browser
headers = {
   "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}


# 3. Fetch the HTML
response = requests.get(url, headers=headers)


if response.status_code == 200:
   soup = BeautifulSoup(response.text, 'html.parser')


   # 4. Find the specific container list
   # Your source shows the data is inside <ul class="list-group mb-4 not-premium">
   # We select all list items (li) inside that list
   list_items = soup.select('ul.list-group li.list-group-item')


   data = []


   for item in list_items:
       try:
           # --- Extract Player Name ---
           # Look for the <a> tag with class 'link'
           player_tag = item.find('a', class_='link')
           if not player_tag:
               continue # Skip rows without a player (like banners)
           player_name = player_tag.get_text(strip=True)


           # --- Extract Rank ---
           # Look for the div with class 'fs-3' (font-size 3)
           rank_tag = item.find('div', class_='fs-3')
           rank = rank_tag.get_text(strip=True) if rank_tag else None
           salary_tag = item.find('span', class_='medium')
           salary = salary_tag.get_text(strip=True) if salary_tag else "0"
           info_tag = item.find('small')
           team = "N/A"
           position = "N/A"


           if info_tag:
               info_text = info_tag.get_text(strip=True)
               if "," in info_text:
                   parts = info_text.split(',')
                   team = parts[0].strip()
                   position = parts[1].strip()
               else:
                   team = info_text


           # Append to our data list
           data.append({
               "Rank": rank,
               "Player": player_name,
               "Team": team,
               "Position": position,
               "AAV Salary": salary
           })


       except Exception as e:
           # Skip any malformed rows silently
           continue


   # 5. Convert to Pandas DataFrame
   df = pd.DataFrame(data)


   # --- Data Cleaning ---
   # Convert Salary to a real number (remove '$' and ',')
   df['AAV Salary Value'] = df['AAV Salary'].astype(str).str.replace('$', '').str.replace(',', '')
   df['AAV Salary Value'] = pd.to_numeric(df['AAV Salary Value'], errors='coerce')


   # Display the first 10 rows
   print(f"Successfully scraped {len(df)} players.")
   display(df.head(510))


else:
   print(f"Failed to retrieve page. Status code: {response.status_code}")

import pandas as pd


url_bbref = "https://www.basketball-reference.com/leagues/NBA_2025_advanced.html"


tables = pd.read_html(url_bbref, header=0)
df_ast = tables[0]


df_ast = df_ast[df_ast['Player'] != 'Player']
df_ast = df_ast[['Player', 'Team', 'AST%']]
df_ast['AST%'] = pd.to_numeric(df_ast['AST%'], errors='coerce')
df_ast = df_ast.sort_values('AST%', ascending=False).reset_index(drop=True)


print(f"Successfully scraped {len(df_ast)} players.")
display(df_ast)

import unicodedata
import pandas as pd

# ---------- Helper: remove accents ----------
def remove_accents(name):
    return ''.join(
        c for c in unicodedata.normalize('NFD', str(name))
        if unicodedata.category(c) != 'Mn'
    )

# ---------- Clean BOTH datasets ----------
df['Player'] = df['Player'].apply(remove_accents)
df_ast['Player'] = df_ast['Player'].apply(remove_accents)

# Optional: remove suffixes (helps matching)
df['Player'] = df['Player'].str.replace(r'\b(Jr\.?|Sr\.?|III|II)\b', '', regex=True).str.strip()
df_ast['Player'] = df_ast['Player'].str.replace(r'\b(Jr\.?|Sr\.?|III|II)\b', '', regex=True).str.strip()

# ---------- Fix df_ast (keep 1 row per player, prefer 2TM) ----------
df_ast['is_2TM'] = df_ast['Team'] == '2TM'
df_ast = df_ast.sort_values(by='is_2TM', ascending=False)

df_ast = df_ast.drop_duplicates(subset='Player', keep='first')
df_ast = df_ast.drop(columns='is_2TM')

# ---------- Ensure df (salary) has no duplicates ----------
df = df.drop_duplicates(subset='Player')

# ---------- Get TOP 100 salaries ----------
df_top100 = df.sort_values('AAV Salary Value', ascending=False).head(100)

# ---------- Merge ----------
df_merged = pd.merge(df_top100, df_ast, on='Player', how='left')

# ---------- Final formatting ----------
df_merged = df_merged.sort_values('AAV Salary Value', ascending=False).reset_index(drop=True)

# ---------- Display ----------
print(f"Final dataset has {len(df_merged)} players.")
display(df_merged)

df_merged.to_excel('nba_ast_salary.xlsx', index=False)
from google.colab import files
files.download("nba_ast_salary.xlsx")

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

plt.scatter(
    df_merged["AST%"],
    df_merged["AAV Salary Value"]
)

plt.xlabel("Assist Percentage (AST%)")
plt.ylabel("Average Annual Salary ($)")
plt.title("NBA Salary vs Assist Percentage (2025)")

plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,7))

sns.regplot(
    data=df_merged,
    x="AST%",
    y="AAV Salary Value",
    scatter=False
)

sns.scatterplot(
    data=df_merged,
    x="AST%",
    y="AAV Salary Value",
    hue="Position",
    alpha=0.7
)

plt.xlabel("Assist Percentage (AST%)")
plt.ylabel("Average Annual Salary ($)")
plt.title("NBA Salary vs Assist Percentage (2025)")
plt.legend(title="Position")

plt.show()



import pandas as pd




url_bbref = "https://www.basketball-reference.com/leagues/NBA_2025_advanced.html"




tables = pd.read_html(url_bbref, header=0)
df_blk = tables[0]




df_blk = df_blk[df_blk['Player'] != 'Player']
df_blk = df_blk[['Player', 'Team', 'BLK%']]
df_blk['BLK%'] = pd.to_numeric(df_blk['BLK%'], errors='coerce')
df_blk = df_blk.sort_values('BLK%', ascending=False).reset_index(drop=True)




print(f"Successfully scraped {len(df_blk)} players.")
display(df_blk)

import unicodedata
import pandas as pd

# ---------- Helper: remove accents ----------
def remove_accents(name):
    return ''.join(
        c for c in unicodedata.normalize('NFD', str(name))
        if unicodedata.category(c) != 'Mn'
    )

# ---------- Clean BOTH datasets ----------
df['Player'] = df['Player'].apply(remove_accents)
df_blk['Player'] = df_blk['Player'].apply(remove_accents)

# Optional: remove suffixes (helps matching)
df['Player'] = df['Player'].str.replace(r'\b(Jr\.?|Sr\.?|III|II)\b', '', regex=True).str.strip()
df_blk['Player'] = df_blk['Player'].str.replace(r'\b(Jr\.?|Sr\.?|III|II)\b', '', regex=True).str.strip()

# ---------- Fix df_ast (keep 1 row per player, prefer 2TM) ----------
df_blk['is_2TM'] = df_blk['Team'] == '2TM'
df_blk = df_blk.sort_values(by='is_2TM', ascending=False)

df_blk = df_blk.drop_duplicates(subset='Player', keep='first')
df_blk = df_blk.drop(columns='is_2TM')

# ---------- Ensure df (salary) has no duplicates ----------
df = df.drop_duplicates(subset='Player')

# ---------- Get TOP 100 salaries ----------
df_top100 = df.sort_values('AAV Salary Value', ascending=False).head(100)

# ---------- Merge ----------
df_merged = pd.merge(df_top100, df_blk, on='Player', how='left')

# ---------- Final formatting ----------
df_merged = df_merged.sort_values('AAV Salary Value', ascending=False).reset_index(drop=True)

# ---------- Display ----------
print(f"Final dataset has {len(df_merged)} players.")
display(df_merged)

df_merged.to_excel('nba_blk_salary.xlsx', index=False)
from google.colab import files
files.download("nba_blk_salary.xlsx")
